#!/bin/bash

# Check if any sinks aren't muted
if pactl list sinks | grep Mute | grep no
then
	state=true
else
	state=false
fi

# Set all sinks to state
for sink in $(pactl list sinks | grep Name | sed 's/[^ ]* *//')
do
	pactl set-sink-mute "$sink" "$state";
done
